// node --experimental-strip-types e2e/prescreen.test.mjs
import { prescreen, detectRemote, detectRole, detectSeniority, titleGate } from '../src/shared/prescreen.ts'

const results = []
const check = (name, cond, extra) => {
  results.push(cond)
  console.log((cond ? 'PASS ' : 'FAIL ') + name + (extra !== undefined && !cond ? '  -> ' + JSON.stringify(extra) : ''))
}

// --- remote ---
check('hybrid TR wording', detectRemote('Haftada 2 gün ofis (Maslak), 3 gün uzaktan çalışma.', 'remote').remote === 'hybrid')
check('hybrid EN wording', detectRemote('We offer a hybrid model: 3 days a week in the office.', 'remote').remote === 'hybrid')
check('residency requirement => onsite', detectRemote("İstanbul'da ikamet eden adaylar tercih edilir. Uzaktan çalışma.", 'remote').remote === 'onsite')
check('full remote TR', detectRemote("Tamamen uzaktan, Türkiye'nin her yerinden başvurabilirsiniz.", 'unknown').remote === 'verified')
check('full remote EN', detectRemote('This is a fully remote position within Türkiye.', 'unknown').remote === 'verified')
check('silent text + hybrid label', detectRemote('Jira ve SQL bilen iş analisti arıyoruz.', 'hybrid').remote === 'hybrid')
check('silent text + remote label stays unknown', detectRemote('Jira ve SQL bilen iş analisti arıyoruz.', 'remote').remote === 'unknown')
check('"gerektiğinde ofiste" => hybrid', detectRemote('Uzaktan çalışma, gerektiğinde ofiste bulunma.', 'remote').remote === 'hybrid')
check('text match => source text', detectRemote('We offer a hybrid model: 3 days a week in the office.', 'remote').source === 'text')
check('silent text + label => source label', detectRemote('Jira ve SQL bilen iş analisti arıyoruz.', 'onsite').source === 'label')
check('unknown => no source', detectRemote('Jira ve SQL bilen iş analisti arıyoruz.', 'remote').source === null)
const preSrc = prescreen({ title: 'Business Analyst', workplaceType: 'hybrid', location: 'Ankara, Türkiye', descriptionMd: 'Jira ve SQL bilen iş analisti arıyoruz. Gereksinim analizi, user story yazımı. En az 2 yıl deneyim.' })
check('prescreen carries remoteSource + version', preSrc.remoteSource === 'label' && preSrc.v >= 2, preSrc)

// --- role ---
check('BA core', detectRole('Business Analyst', 'gereksinim analizi, backlog, user story').role === 'core')
check('İş Analisti core', detectRole('Kıdemli İş Analisti', 'gereksinim analizi').role === 'core')
check('technical BA adjacent', detectRole('Technical Business Analyst', 'requirements').role === 'adjacent')
check('sistem analisti adjacent', detectRole('Sistem Analisti', 'analiz').role === 'adjacent')
check('support mismatch', detectRole('Technical Support Specialist', 'ticket').role === 'mismatch')
check('developer mismatch', detectRole('Senior Software Developer', 'java').role === 'mismatch')
check('PM core (not managerial)', detectRole('Product Manager', 'roadmap').role === 'core')
const hidden = detectRole('Business Analyst', 'Gelen ticket kayıtlarını çözer, SLA takibi yapar, çağrı merkezi ile koordinasyon, arıza eskalasyonu, vardiya planı, L1 destek. Ticket kapatma.')
check('hidden support role flagged', hidden.hiddenSupport === true && hidden.role === 'bridge', hidden)
check('data analyst bridge', detectRole('Data Analyst', 'sql').role === 'bridge')

// --- seniority ---
check('2-4 yıl match', detectSeniority('BA', 'En az 2 yıl iş analizi tecrübesi.').seniority === 'match')
check('5+ years stretch', detectSeniority('BA', 'Minimum 5+ years of experience as a BA.').seniority === 'stretch')
check('8 yıl over', detectSeniority('BA', 'En az 8 yıl deneyim.').seniority === 'over')
check('range 3-5 takes min', detectSeniority('BA', '3-5 yıl tecrübe').seniority === 'match')
check('range 0-2 years is match, not junior', detectSeniority('Product Analyst', 'Experience: 0–2 years of experience in product or a strong portfolio').seniority === 'match')
check('range 0-1 year still match', detectSeniority('BA', '0-1 yıl tecrübe').seniority === 'match')
const bonusFalse = prescreen({ title: 'Product Analyst', workplaceType: 'remote', location: 'Türkiye', descriptionMd: 'Fully remote. High-energy team building a utility app for consumers. 1-3 years experience. SQL nice to have.' })
check('no energy bonus for "high-energy team"/"utility app"', !bonusFalse.bonuses.includes('enerji/utility'), bonusFalse.bonuses)
const bonusTrue = prescreen({ title: 'Business Analyst', workplaceType: 'remote', location: 'Ankara, Türkiye', descriptionMd: 'Uzaktan çalışma. Elektrik dağıtım şirketlerine OMS/WFM çözümleri. 2 yıl tecrübe. SQL.' })
check('energy bonus for elektrik dağıtım / OMS', bonusTrue.bonuses.includes('enerji/utility'), bonusTrue.bonuses)
check('head of => over', detectSeniority('Head of Product', 'x').seniority === 'over')
check('Product Manager is not managerial', detectSeniority('Product Manager', 'En az 3 yıl deneyim').seniority === 'match')
check('stajyer under', detectSeniority('Business Analyst Intern', 'x').seniority === 'under')
check('no years unknown', detectSeniority('BA', 'Jira bilen').seniority === 'unknown')
check('ignores "2 yıl garanti" without context', detectSeniority('BA', 'Ürünümüz 2 yıl garantili. Aday tecrübeli olmalı.').years === null)

// --- title gate ---
check('gate keeps BA', titleGate('Business Analyst') === null)
check('gate keeps Software Business Analyst', titleGate('Software Business Analyst') === null)
check('gate keeps İş Analisti', titleGate('Kıdemli İş Analisti') === null)
check('gate keeps Product Manager', titleGate('Product Manager, Risk & Resilience') === null)
check('gate keeps Ürün Yöneticisi', titleGate('Ürün Yöneticisi') === null)
check('gate keeps Requirement Engineering Specialist (adjacent)', titleGate('Requirement Engineering Specialist') === null)
check('gate keeps unknown-but-plausible (Süreç Yönetimi Uzmanı)', titleGate('Süreç Yönetimi ve Mimarisi Uzmanı') === null)
check('gate skips Saha Satış', titleGate('Saha Satış Temsilcisi - İstanbul Avrupa') !== null)
check('gate skips SEO Uzmanı', titleGate('SEO Uzmanı') !== null)
check('gate skips E-ticaret Uzmanı', titleGate('E-ticaret Uzmanı') !== null)
check('gate skips FP&A Analyst', titleGate('Senior FP&A Analyst') !== null)
check('gate skips EHS Analyst', titleGate('Senior EHS Analyst') !== null)
check('gate skips Azure Solutions Architect - Presales', titleGate('Azure Solutions Architect - Presales') !== null)
check('gate skips Agent Solutions Engineer', titleGate('Agent Solutions Engineer') !== null)
check('gate skips AI Trainer / annotator', titleGate('AI Trainer - Freelance Data Annotator') !== null)
check('gate skips Head-Software (Chapter Lead)', titleGate('Head-Software (Chapter Lead)') !== null)
check('gate skips Customer Development Manager', titleGate('Customer Development Manager') !== null)
check('gate skips Ecommerce Product Catalog Analyst', titleGate('Ecommerce Product Catalog & Research Analyst') !== null)
check('gate skips unrelated generic title', titleGate('Warehouse Shift Supervisor') !== null)
check('gate skips SAP Payroll consultant (adjacent, wrong domain)', titleGate('Türkiye - SAP Payroll & HCM functional consultant') !== null)
check('gate skips ERP Consultant (Finance)', titleGate('ERP Consultant (Finance)') !== null)
check('gate skips İdari İşler ve Operasyon Yöneticisi', titleGate('İDARİ İŞLER VE OPERASYON YÖNETİCİSİ') !== null)
check('gate skips Solution Engineer (Presales)', titleGate('Solution Engineer (Presales)') !== null)
check('gate skips Industry Principal', titleGate('Industry Principal, MMM') !== null)
check('gate skips Manager, Inventory Performance', titleGate('Manager, Inventory Performance') !== null)
check('gate skips Bordro Uzmanı', titleGate('Bordro Uzmanı') !== null)
check('gate skips Uzman ELD Teknikeri', titleGate('Uzman ELD Teknikeri') !== null)
check('gate skips Patient Journey Partner', titleGate('Patient Journey Partner (Onco / Breast)') !== null)
check('gate keeps Associate Product Manager', titleGate('Associate Product Manager') === null)
check('gate keeps Product Senior Analyst', titleGate('Product Senior Analyst') === null)
check('gate keeps Customer Solutions Process Manager (bridge)', titleGate('Customer Solutions Process Manager') === null)
const gatedPre = prescreen({ title: 'Dairy Farm Advisor Turkey', workplaceType: 'hybrid', location: 'İzmir, Türkiye', descriptionMd: 'Hibrit çalışma. Süt çiftlikleri için danışmanlık. Gereksinim analizi, raporlama. 2 yıl tecrübe. Jira.' })
check('prescreen rejects text-fetched row that fails the title gate', gatedPre.verdict === 'reject' && gatedPre.flags.some((f) => f.startsWith('başlık kapısı')), gatedPre)
// guest collector rows carry no label: location is the only hint when the text is silent
const noLabelTR = prescreen({ title: 'Business Analyst', workplaceType: 'unknown', location: 'Türkiye', descriptionMd: 'Jira ve SQL bilen iş analisti arıyoruz. Gereksinim analizi, user story yazımı. En az 2 yıl deneyim.' })
check('no label + country-only location: capped 65, remote hint in reasons', noLabelTR.remote === 'unknown' && noLabelTR.score <= 65 && noLabelTR.reasons.some((r) => /şehirsiz/.test(r)), noLabelTR)
const noLabelAnk = prescreen({ title: 'Business Analyst', workplaceType: 'unknown', location: 'Ankara, Türkiye', descriptionMd: 'Jira ve SQL bilen iş analisti arıyoruz. Gereksinim analizi, user story yazımı. En az 2 yıl deneyim.' })
check('no label + home city: capped 60, review', noLabelAnk.score <= 60 && noLabelAnk.verdict === 'review' && noLabelAnk.homeCity, noLabelAnk)
const noLabelIst = prescreen({ title: 'Business Analyst', workplaceType: 'unknown', location: 'İstanbul, Türkiye', descriptionMd: 'Jira ve SQL bilen iş analisti arıyoruz. Gereksinim analizi, user story yazımı. En az 2 yıl deneyim.' })
check('no label + other city: capped 50', noLabelIst.score <= 50 && noLabelIst.score < noLabelAnk.score, noLabelIst)
check('gate skips pharma product rep', titleGate('Ürün Uzmanı - Onkoloji (Ankara)') !== null)
check('gate skips medical product team', titleGate('Kalp Damar Cerrahisi Ürün Yönetimi Takım Üyesi') !== null)
check('gate skips Tıbbi Ürün Tanıtım Sorumlusu', titleGate('Tıbbi Ürün Tanıtım Sorumlusu (İstanbul Anadolu Yakası)') !== null)
check('gate skips Road Machinery Product Manager', titleGate('Road Machinery Product Manager') !== null)
check('gate skips SAP ABAP Geliştirme Uzmanı', titleGate('SAP ABAP Geliştirme Uzmanı') !== null)
check('gate keeps Proje Yöneticisi (software project roles are adjacent)', titleGate('Proje Yöneticisi') === null)
check('gate skips Üretim Proje Yöneticisi (non-software domain)', titleGate('Üretim Proje Yöneticisi') !== null && titleGate('İnşaat Proje Sorumlusu') !== null)
check('detectRole: Proje Yöneticisi → adjacent', detectRole('Proje Yöneticisi', '').role === 'adjacent')
const remoteBonus = prescreen({ title: 'Product Owner', workplaceType: 'unknown', location: 'Türkiye', descriptionMd: 'Tamamen uzaktan, Türkiye içinden. Backlog, paydaş, sprint. 3 yıl tecrübe. Jira.' })
check('full remote gets the first-preference bonus', remoteBonus.bonuses.includes('tam remote (birinci tercih)') && remoteBonus.verdict === 'candidate', remoteBonus)
check('gate skips Bölge Operasyon Yöneticisi', titleGate('Bölge Operasyon Yöneticisi (İç Anadolu/Ankara)') !== null)
check('gate skips CEO Office Analyst', titleGate('CEO Office Analyst') !== null)
check('gate keeps Business Systems Analyst', titleGate('Business Systems Analyst, Enterprise Platforms') === null)
check('gate keeps Product & Growth Analyst', titleGate('Product & Growth Analyst') === null)
check('gate skips Bangkok-based', titleGate('Business Analyst (Supply Analytics, Bangkok-based, Relocation Provided)') !== null)
check('gate skips Senior PM (Bangkok-based)', titleGate('Senior Product Manager (Bangkok-based)') !== null)
check('gate keeps Ankara-based', titleGate('Business Analyst (Ankara-based)') === null)
check('gate keeps Remote-based wording', titleGate('Remote-based Product Owner') === null)
check('gate keeps Raporlama Sorumlusu (bridge)', titleGate('Raporlama Sorumlusu') === null)
check('gate keeps Süreç Geliştirme Sorumlusu (bridge)', titleGate('Süreç Geliştirme Sorumlusu') === null)
check('gate keeps Solution Consultant (adjacent)', titleGate('Solution Consultant') === null)
check('gate keeps Information System Specialist (bridge)', titleGate('Information System Specialist') === null)
check('gate keeps Commercial Product Manager (core)', titleGate('Commercial Product Manager, Türkiye & ME') === null)
check('gate keeps Business Analyst (Leasing & Factoring)', titleGate('Business Analyst (Leasing & Factoring)') === null)
check('gate skips Proje Mühendisi', titleGate('Proje Mühendisi') !== null)
check('gate skips Çağrı Merkezi', titleGate('Çağrı Merkezi Müşteri Danışmanı - Havacılık') !== null)
check('gate skips Head of Product', titleGate('Head of Product') !== null)
check('gate skips Business Analyst Intern', titleGate('Business Analyst Intern') !== null)
check('gate skips Database Administrator', titleGate('Database Administrator') !== null)
check('gate skips Gamer part-time', titleGate('Gamer / Oyun Editörü Arıyoruz (Part-Time & Remote)') !== null)
check('gate skips Technical Support Specialist', titleGate('Technical Support Specialist') !== null)

// --- full prescreen ---
const hybridIst = prescreen({ title: 'Business Analyst', workplaceType: 'remote', location: 'İstanbul, Türkiye', descriptionMd: 'B2B SaaS ürünümüz için iş analisti. Haftada 2 gün ofis, 3 gün uzaktan. En az 2 yıl tecrübe. Jira, SQL.' })
check('hybrid İstanbul: allowed but capped 60, review', hybridIst.remote === 'hybrid' && !hybridIst.homeCity && hybridIst.score <= 60 && hybridIst.verdict !== 'reject', hybridIst)
const hybridAnk = prescreen({ title: 'Business Analyst', workplaceType: 'hybrid', location: 'Ankara, Türkiye', descriptionMd: 'B2B SaaS ürünümüz için iş analisti. Haftada 2 gün ofis, 3 gün uzaktan. En az 2 yıl tecrübe. Jira, SQL.' })
const hybridIzm = prescreen({ title: 'Business Analyst', workplaceType: 'hybrid', location: 'İzmir, Türkiye', descriptionMd: 'B2B SaaS ürünümüz için iş analisti. Haftada 2 gün ofis, 3 gün uzaktan. En az 2 yıl tecrübe. Jira, SQL.' })
check('hybrid İzmir counts as home city (same as Ankara)', hybridIzm.homeCity && hybridIzm.homeCityName === 'İzmir' && hybridIzm.score === hybridAnk.score && hybridIzm.verdict === 'candidate', hybridIzm)
const onsiteAyd = prescreen({ title: 'Business Analyst', workplaceType: 'onsite', location: 'Aydın, Türkiye', descriptionMd: 'Ofisten çalışma. İş analisti. En az 2 yıl tecrübe. Jira, SQL, gereksinim analizi.' })
check('onsite Aydın: home city, candidate', onsiteAyd.homeCity && onsiteAyd.verdict === 'candidate', onsiteAyd)
check('hybrid Ankara: top priority, candidate', hybridAnk.remote === 'hybrid' && hybridAnk.homeCity && hybridAnk.verdict === 'candidate' && hybridAnk.score > hybridIst.score, hybridAnk)
const onsiteIst = prescreen({ title: 'Business Analyst', workplaceType: 'onsite', location: 'İstanbul, Türkiye', descriptionMd: 'Ofisten çalışma. İş analisti. En az 2 yıl tecrübe. Jira, SQL, gereksinim analizi.' })
check('onsite İstanbul: reject (<=25)', onsiteIst.remote === 'onsite' && onsiteIst.score <= 25 && onsiteIst.verdict === 'reject', onsiteIst)
const onsiteAnk = prescreen({ title: 'Business Analyst', workplaceType: 'onsite', location: 'Ankara, Türkiye', descriptionMd: 'Ofisten çalışma. İş analisti. En az 2 yıl tecrübe. Jira, SQL, gereksinim analizi.' })
check('onsite Ankara: accepted city, candidate (no cap)', onsiteAnk.remote === 'onsite' && onsiteAnk.homeCity && onsiteAnk.verdict === 'candidate', onsiteAnk)
check('onsite Aydın scores at most onsite Ankara', onsiteAyd.score <= onsiteAnk.score, { ayd: onsiteAyd.score, ank: onsiteAnk.score })
const salaryLow = prescreen({ title: 'Business Analyst', workplaceType: 'remote', location: 'Türkiye', descriptionMd: 'Tamamen uzaktan. İş analisti. En az 2 yıl tecrübe. Jira. Maaş: 60.000 TL brüt.' })
check('salary below 90k flagged', salaryLow.flags.some((f) => f.startsWith('maaş 90k altı')) && salaryLow.salaryTl === 60000, salaryLow)
const salaryOk = prescreen({ title: 'Business Analyst', workplaceType: 'remote', location: 'Türkiye', descriptionMd: 'Tamamen uzaktan. İş analisti. En az 2 yıl tecrübe. Jira. Ücret 90k-120k TL.' })
const salaryFalse = prescreen({ title: 'Business Analyst', workplaceType: 'remote', location: 'Türkiye', descriptionMd: 'Tamamen uzaktan. Platformumuzu 50k+ kullanıcı kullanıyor, 15 bin şirket. İş analisti. 2 yıl tecrübe. Jira.' })
check('"50k+ kullanıcı" is not a salary', salaryFalse.salaryTl === undefined && !salaryFalse.flags.some((f) => f.startsWith('maaş')), salaryFalse)
const salaryLira = prescreen({ title: 'Business Analyst', workplaceType: 'remote', location: 'Türkiye', descriptionMd: 'Tamamen uzaktan. İş analisti. 2 yıl tecrübe. Maaş: 60.000 ₺ brüt.' })
check('₺ amount detected', salaryLira.salaryTl === 60000, salaryLira.salaryTl)
const pmTr = prescreen({ title: 'Ürün Müdürü', workplaceType: 'remote', location: 'Türkiye', descriptionMd: 'Tamamen uzaktan B2B SaaS. Ürün yol haritası, backlog, gereksinim analizi. En az 3 yıl tecrübe. Jira, SQL.' })
check('Ürün Müdürü is core PM, not managerial cap', pmTr.verdict === 'candidate' && pmTr.seniority !== 'over' && pmTr.score > 60, pmTr)
check('salary 120k bonus', salaryOk.bonuses.some((b) => b.startsWith('maaş yazılı')) && salaryOk.salaryTl === 120000, salaryOk)
const hybDetail = prescreen({ title: 'Business Analyst', workplaceType: 'hybrid', location: 'Ankara, Türkiye', descriptionMd: 'Hibrit model: haftada 2 gün ofis, 3 gün uzaktan. İş analisti. En az 2 yıl tecrübe.' })
check('hybrid detail extracted', hybDetail.hybridDetail === 'haftada 2 gün ofis', hybDetail.hybridDetail)
const partTime = prescreen({ title: 'Business Analyst', workplaceType: 'remote', location: 'Türkiye', descriptionMd: 'Tamamen uzaktan, yarı zamanlı freelance iş analisti. 2 yıl tecrübe. Jira.' })
check('part-time capped 25', partTime.score <= 25 && partTime.flags.includes('yarı zamanlı / freelance'), partTime)
const seniorAd = prescreen({ title: 'Senior Business Analyst', workplaceType: 'remote', location: 'Türkiye', descriptionMd: 'Tamamen uzaktan. En az 8 yıl iş analizi tecrübesi. Jira, SQL, gereksinim analizi, user story.' })
check('8+ years: -20 but not rejected outright', seniorAd.seniority === 'over' && seniorAd.verdict !== 'reject', seniorAd)
check('QA title is bridge now, not mismatch', detectRole('Test Analyst', 'test senaryoları').role === 'bridge')
check('gate keeps Lead Business Analyst (senior IC)', titleGate('Lead Business Analyst') === null)
check('gate keeps Junior Business Analyst', titleGate('Junior Business Analyst') === null)
check('gate keeps Insurance Product Manager (sector irrelevant)', titleGate('Insurance Product Manager') === null)
check('gate keeps Insurance Product Manager / Underwriter (core title, sector irrelevant)', titleGate('Insurance Product Manager / Underwriter') === null)
const remoteOnly = prescreen({ title: 'Business Analyst', workplaceType: 'hybrid', location: 'Ankara, Türkiye', descriptionMd: 'Hibrit çalışma. İş analisti. En az 2 yıl tecrübe. Jira.' }, { homeCities: ['Ankara'], acceptHybrid: false })
check('acceptHybrid=false keeps the old cap', remoteOnly.score <= 25, remoteOnly)
const good = prescreen({ title: 'Product Owner', workplaceType: 'remote', descriptionMd: "Tamamen uzaktan, Türkiye'nin her yerinden. Enerji sektörüne yönelik B2B SaaS. En az 2 yıl ürün/analiz tecrübesi. Jira, SQL, Figma. Maaş: rekabetçi." })
check('good remote PO is candidate', good.verdict === 'candidate' && good.score >= 70 && good.remote === 'verified' && good.role === 'core' && good.seniority === 'match', good)
const silent = prescreen({ title: 'Business Analyst', workplaceType: 'remote', descriptionMd: 'İş analisti arıyoruz. Gereksinim analizi, süreç iyileştirme. 2 yıl tecrübe. Jira.' })
check('remote-label + silent text: mild cap 70', silent.score <= 70 && silent.score > 55 && silent.remote === 'unknown', silent)
const silentHybOther = prescreen({ title: 'Business Analyst', workplaceType: 'hybrid', location: 'İstanbul, Türkiye', descriptionMd: 'İş analisti arıyoruz. Gereksinim analizi, süreç iyileştirme. 2 yıl tecrübe. Jira.' })
check('hybrid-label other city + silent text: capped 60', silentHybOther.score <= 60 && silentHybOther.verdict !== 'reject', silentHybOther)
const shift = prescreen({ title: 'Product Support Analyst', workplaceType: 'remote', descriptionMd: 'Fully remote. 7/24 vardiyalı destek. Ajans bünyesinde bordrolu. Fluent English required for international clients. 1-3 years.' })
check('flags collected', shift.flags.includes('vardiya/nöbet') && shift.flags.includes('ajans/danışmanlık üzerinden') && shift.flags.includes('günlük/sözlü İngilizce olabilir') && shift.verdict === 'reject', shift)
const support = prescreen({ title: 'Technical Support Engineer', workplaceType: 'remote', descriptionMd: 'Fully remote position. At least 2 years of experience in B2B SaaS support. Jira and SQL.' })
check('mismatch capped at 30', support.score <= 30 && support.verdict === 'reject', support)
check('no description => null', prescreen({ title: 'x', workplaceType: 'remote', descriptionMd: null }) === null)

const failed = results.filter((r) => !r).length
console.log(`\n${results.length - failed}/${results.length} passed`)
process.exit(failed ? 1 : 0)
